package com.assignment.account.service;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Request class for transaction creation.
 */
@Data
@AllArgsConstructor
public class TransactionRequest {

    /**
     * The ID of the customer associated with the transaction.
     */
    private long customerId;

    /**
     * The amount to be processed in the transaction.
     */
    private double amount;

    // Getters and setters are generated by Lombok's @Data annotation.
}
